### ISSUE TITLE
download issue; hmr2_data.tar.gz

### ISSUE THREAD

**Issue by chojinie** [statho/ScoreHMR#22]
Hi @statho and author,
I'm Jin.

Thank you for share nice work!

I'm having trouble with the command to download the file: hmr2_data.tar.gz. When I attempt to download the remote file from https://people.eecs.berkeley.edu/~jathushan/projects/4dhumans/hmr2_data.tar.gz to /root/.cache/4DHumans/hmr2_data.tar.gz, it doesn't work. It seems like the download from this path is blocked. Is there another way I can obtain this file?

Or, if my understanding is incorrect, please let me know your thoughts

![image](https://github.com/statho/ScoreHMR/assets/106041887/35845950-0a70-4e2b-880e-ce21609d1356)

Best Regards,

**Comment by statho** [comment]
Hi Jin! The demo code should automatically download the zip file in `<home_dictectory>/.cache/4DHumans`. 

Not sure why this is the `/root` for you. Can you make sure use have access to this directory? It can be the case that the file is not downloaded because you don't have write permission for `/root`. I ran the code from my end just now, and it works.
