### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by Fouksi** [statho/ScoreHMR#25]
Great paper!

I can't find your MPII annotations - in which method did you use to annotate it?

Thank you.

**Comment by statho** [comment]
Thanks! We used both EFT and SPIN fits for experiments in our paper. 

The released code uses EFT fits as training with them performs slightly better. We did not release the EFT fits for MPII since training only with H36M, MPI-INF-3DPH and COCO had the same performance. See [here](https://github.com/statho/ScoreHMR/blob/master/score_hmr/configs/base.yaml#L2) for the datasets and their ratios used during training -- ratios are the ones proposed in [PARE](https://github.com/mkocabas/PARE). 

For experiments with SPIN fits we used the datasets (which include MPII) and ratios as seen [here](https://github.com/nkolot/ProHMR/blob/master/prohmr/configs/prohmr.yaml#L2) to fairly compare with [ProHMR](https://github.com/nkolot/ProHMR) that also uses SPIN fits during training. You can get the SPIN fits for all datasets, including MPII by following the instructions [here](https://github.com/nkolot/ProHMR/blob/master/dataset_preprocessing/README.md).

**Comment by Fouksi** [comment]
And where can I find the validation set for COCO-EFT?
The npz file you supplied doesn't have the pose & shape parameters.
Thanks.

**Comment by statho** [comment]
We only used the 2D keypoints from the validation set of COCO for monitoring purposes during training, so I don't have an npz file with the COCO-val EFT fits.

You can check out the [official EFT repo](https://github.com/facebookresearch/eft/tree/main) if you need the pseudo-GT for some reason.
