### ISSUE TITLE
VRAM Requirements for Inference 

### ISSUE THREAD

**Issue by Marlod390** [statho/ScoreHMR#4]
Dear Author,

First of all, thank you for your excellent work. I encountered an Out of Memory (OOM) error while doing inference using the provided demo script. So I'm curious how much VRAM is needed for inference. I would be grateful if you could provide information on this.

**Comment by statho** [comment]
Thank you for appreciating our work!

1. The demo with videos requires 12.7 GB of GPU memory (due to tracking with 4D Humans).

2. The demo with images requires 14.4 GB of GPU memory, and uses several models:
- ViTDet : 2.8 GB
- ViTPose : 2.6 GB
- HMR 2.0 : 3 GB
- ScoreHMR (including PARE backbone) : 0.4 GB 

Furthermore, the input images have high resolution (6K x 4K), and contain a lot of people.

To reduce the GPU memory usage, I suggest to: 
a) store detections from ViTDet and ViTPose first, and then run HMR 2.0 and ScoreHMR, OR
b) run ScoreHMR on top of PARE regression, OR
c) try the existing code on lower resolution images
